### ISSUE TITLE
Declared opportunities don't work on Python

### ISSUE THREAD

**Issue by Hell576** [MicrosoftEdge/EdgeWebDriver#14]
**I was try to use this manual: https://docs.microsoft.com/en-us/microsoft-edge/webdriver-chromium/?tabs=python
And wrote this**

from selenium import webdriver 
from selenium.webdriver.common.by import By
from selenium.webdriver.edge.options import Options

webdriver_opt = Options()
webdriver_opt.add_argument('headless')
webdriver_opt.add_argument('disable-gpu')

driver = webdriver.Edge(executable_path="./msedgedriver.exe", options=webdriver_opt)
**It gives me an error:**
Traceback (most recent call last):
  File "W:\Users\xxx\Desktop\venv\work_dir\jscrap\jscrap.py", line 38, in <module>
    webdriver_opt.add_argument('headless')
AttributeError: 'Options' object has no attribute 'add_argument'

**even if I comment these lines below:**
webdriver_opt.add_argument('headless')
webdriver_opt.add_argument('disable-gpu')
**except this**
driver = webdriver.Edge(executable_path="./msedgedriver.exe", options=webdriver_opt)

**There will be such error:**
Traceback (most recent call last):
  File "W:\Users\xxx\Desktop\venv\work_dir\jscrap\jscrap.py", line 43, in <module>
    driver = webdriver.Edge(executable_path="./msedgedriver.exe", options=webdriver_opt)
TypeError: __init__() got an unexpected keyword argument 'options'

**Comment by bwalderman** [comment]
Closing this issue as this appears to be due to using Selenium 3. Feel free to re-open if the issue persists after upgrading to the latest version.

**Comment by Hell576** [comment]
The problem was really in the version of product, but I faced with problem,
that selenium 4 does not work on python 3.7. There was a need to reinstall
python version higher than 3.7

ср, 27 апр. 2022 г., 20:05 Brandon Walderman ***@***.***>:

**Comment by Hell576** [comment]
And there is a problem with versions in Spyder IDE, the part of anaconda
environment

ср, 27 апр. 2022 г., 21:51 Youth Rise & Fade to Black ***@***.***>:
