### ISSUE TITLE
WebElement.click() stopped working on some fields between Edge 118.0.2088.76 and 120.0.2210.144

### ISSUE THREAD

**Issue by RhythmzZ** [MicrosoftEdge/EdgeWebDriver#139]
Hi 

We have a java selenium framework supporting internal software and using multiple browsers. After an update from Edge 118.0.2088.76 to 120.0.2210.144 WebElement.click() functionality started failing for some fields, tabs etc. As a note we also bumped chrome/firefox and we've only seen the issue with Edge.

Example failure:
  org.openqa.selenium.JavascriptException: javascript error: d.elementFromPoint is not a function

Interestingly enough as a workaround using java script for the clicks works fine:
  JavascriptExecutor jsExecutor = (JavascriptExecutor) driver;
  jsExecutor.executeScript("arguments[0].click();", element);
    
 

I've gone through release notes for Edge and couldn't find anything meaningful I can relate to the specific issue. Is this a known issue? Are there any guidelines I could use to investigate the issue further and find a potential fix? 

Edit: As a note I did try Edge 122 and the issue exists there as well.

Thanks.
